### ISSUE TITLE
TypeError: data type 'pascal' not understood

### ISSUE THREAD

**Issue by GhostDeini** [vetschn/eclabfiles#11]
Hello, i'm getting this error when trying to read MPR files.

in _read_value:
Line 444:   if dtype == "pascal":

TypeError: data type 'pascal' not understood

**Comment by vetschn** [comment]
Hi!

Could you maybe provide the file / code that produces this error for you?

**Comment by GhostDeini** [comment]
Hi, is [this](https://drive.google.com/file/d/1JbLV6ht5UkppyjMuPFXIT5DqxEkAW1wu/view?usp=sharing) file.
I try `df = ecf.to_df("test.mpr")`
also `data, meta = ecf.process("test.mpr")`
but I get the same error with both of them.

I really do not understand how to use the yadg electrochem parser, could you please give me some example? Thank you.

**Comment by vetschn** [comment]
I'm sorry, but I can't reproduce this error with version `0.4.1` from PyPI. The processing and conversion to DataFrame cause no issues for me.

Please make sure you are using the up-to-date version:
```bash
pip install eclabfiles==0.4.1
```

You can find more information on how to use `yadg` in [the project's documentation](https://dgbowl.github.io/yadg/master/usage.html), where you can also find an [interactive example](https://mybinder.org/v2/zenodo/10.5281/zenodo.6351210/?labpath=index.ipynb)
