### ISSUE TITLE
"Error: 51" when reading .mpr file (technique=CVA)

### ISSUE THREAD

**Issue by ScottSoren** [vetschn/eclabfiles#15]
As mentioned in the previous issue, I am writing a .mpr reader for [ixdat](https://github.com/ixdat/ixdat) making use of eclabfiles, but get errors on many of the files.
For CVA, I get the error "Error: 51". I get this same error whether using
data, meta = eclabfiles.process("05_O2dose_COox_02_CVA_C01.mpr")
or
df = eclabfiles.to_df("05_O2dose_COox_02_CVA_C01.mpr")

The file is here, along with plots of the data (made with ixdat.Measurement.read("05_O2dose_COox_02_CVA_C01.mpt").plot() as demo'd in "plot_data.py"):
https://www.dropbox.com/scl/fo/cl0cnovmik7pjgcls2l9h/h?rlkey=v93snkrt2rq3uf95au26qdi0o&dl=0

Happy for any help or suggestions!

**Comment by vetschn** [comment]
I replied to your general issue in more detail over at #14 :)

Files generated from the CVA technique are unfortunately not supported by `eclabfiles`. Perhaps you could try with [`galvani`](https://github.com/echemdata/galvani) (This does not allow you to extract the technique parameters, however.)

**Comment by PeterKraus** [comment]
Fixed in https://github.com/dgbowl/yadg/pull/162, available in `yadg-5.1`.
